### ISSUE TITLE
Missing parts for Mark VII

### ISSUE THREAD

**Issue by XandionKri** [Surasia/Infinite-Spartans-Pack#1]
All four of the S2 chest pieces for Mark VII are not present.

M2497 Pouches
Drachen Ordnance Pack
Packrat Rig
and the Kontakt Plate.

Plus the Vapor Eagle hip attachment.

Plus like 11 sets of gloves.  Mirus, Chiron, Hope's Vice, Ank, Velvet Glove, Flexpoint, Provespa, Crystal, Walle, Ploan, and Corvan.

Another 11 shoulder plates. HIGHCOM Sentinel, Deming, Philes, Cambra, Gidos, Chaka, Farah, Toktu, Renfu, Tomris, and HYBL.

3 sets of knee pads, BF, DP, and AS.

DEACONCREST and STEPSWEEP Wrist attachments.

**Comment by Surasia** [comment]
Will be in prerel_08.

**Comment by Surasia** [comment]
Fixed in prerel08
