### ISSUE TITLE
Torso UV Map

### ISSUE THREAD

**Issue by Phatbuda** [Surasia/Infinite-Spartans-Pack#10]
UV map is slightly off on the torso.
![unknown](https://user-images.githubusercontent.com/113642520/190513516-2267cc5f-8b88-4dd8-86be-97d9874188d3.png)
![unknown (1)](https://user-images.githubusercontent.com/113642520/190513524-90cf63b9-1923-42b8-bb2f-7f868a548093.png)

**Comment by Surasia** [comment]
Fixed, coming with Preview 2
