### ISSUE TITLE
T-Mags Off Material

### ISSUE THREAD

**Issue by Phatbuda** [Surasia/Infinite-Spartans-Pack#11]
Magazine holder is fabric when usually plastic smooth or smooth metal as seen in TAC/Recon Package and TAC/MAT-2519C Communicator.

T-Mags:
![unknown (2)](https://user-images.githubusercontent.com/113642520/190513619-0ccafbbf-be97-4ba2-a0dc-6719eedb6f73.png)

TAC/Recon Package:
![Screenshot 2022-09-15 134040](https://user-images.githubusercontent.com/113642520/190513812-255dd4ec-be72-4ec5-a8cf-b1bf70b4d731.png)

TAC/MAT-2519C Communicator:
![Screenshot 2022-09-15 134056](https://user-images.githubusercontent.com/113642520/190513865-1a1e2a3c-caa6-4556-9af9-a00d10dcb3ef.png)

**Comment by Surasia** [comment]
![image](https://user-images.githubusercontent.com/74399067/190704384-e3538a1f-b3a5-407f-811a-388a1a604a08.png)
fixed :) coming with preview 02
