### ISSUE TITLE
Extra texture node on reach_spartan_helmet_gear_010_s001

### ISSUE THREAD

**Issue by TitanMaster57** [Surasia/Infinite-Spartans-Pack#14]
Lil guy is just chilling

edit: same issue on reach_spartan_hip_gear_004_s001

![image](https://user-images.githubusercontent.com/75141725/190516506-865ab340-b18b-40db-ba51-002f2558885b.png)

**Comment by Surasia** [comment]
fixed, coming with preview 2.0
