### ISSUE TITLE
No shading on reach_spartan_l_knee_prosthetic_sock_001_s001

### ISSUE THREAD

**Issue by TitanMaster57** [Surasia/Infinite-Spartans-Pack#16]
Only a principled BSDF and material output exists, no textures

![image](https://user-images.githubusercontent.com/75141725/190517979-dafe03cd-55e6-45d3-a2b3-b1ed9e3c7c27.png)

**Comment by Surasia** [comment]
This is intentional as the sock is just to avoid clipping and is barely seen in-game.
