### ISSUE TITLE
File format issue?

### ISSUE THREAD

**Issue by Phatbuda** [Surasia/Infinite-Spartans-Pack#19]
File name for the ASG and Mask 1 are too long so Blender ends up cutting off the name and that includes the file format which in this case be ".png"
The model will show the edge wear/dirt and correct colors in evee but once rendering in Cycles it breaks.

Image texture node showing the names being cut off:
![Screenshot 2022-09-16 151834](https://user-images.githubusercontent.com/113642520/190829726-225739db-fefb-43ac-a27d-c88c3e9f4277.png)

Cycles:
![Screenshot 2022-09-16 151808](https://user-images.githubusercontent.com/113642520/190829795-79a00e4b-9cff-484b-bd7f-ff323007f726.png)

Evee:
![Screenshot 2022-09-16 152333](https://user-images.githubusercontent.com/113642520/190830061-16e07d3e-d91a-41ab-84b1-cc96c9e099a5.png)

**Comment by Phatbuda** [comment]
Quick note after looking through the other kneepads I found out that they all have this problem.

**Comment by Surasia** [comment]
This is very weird, I will take a look

**Comment by Surasia** [comment]
It seems like its an issue with the shader itself, even after fixing the PNGs it still has the same issues. I'll talk to ATE about this, so leaving this as "wontfix" for now
