### ISSUE TITLE
Rakshasa Gloves Prosthetic [L] and [R] not correctly rigged

### ISSUE THREAD

**Issue by JustFredrik** [Surasia/Infinite-Spartans-Pack#2]
The Rakshasa Gloves Prosthetic [L] does not respond to the rig and shows up as incorrectly scaled.
The fingers on the right Prosthetic does not deform with the rig and stays in the default A-pose.
![hand issues](https://user-images.githubusercontent.com/54528582/168674866-7acc7efd-5c64-4cc7-95fe-4f71e76e4315.png)

**Comment by AverageTrapEnthusiast** [comment]
Will be addressed in 1.01
Fixes for this particular issue are finished
Finishing fixes for other issues.
