### ISSUE TITLE
Air Assault Helmet coloring

### ISSUE THREAD

**Issue by PrimisGhost** [Surasia/Infinite-Spartans-Pack#21]
Noticed a weird area with the colors on the neck area inside the Air Assault helmet. I switched the colors to make it easier to be able to see where each area is effected. Looks like bits from Zone 1, 3, and 5. (Also they're shaped like teeth, is that intentional?)
![image_2022-09-20_192554347](https://user-images.githubusercontent.com/114036024/191387750-78593486-6013-46ca-a439-6edf4c15d569.png)

**Comment by Surasia** [comment]
Super weird, will look into it

**Comment by Surasia** [comment]
![image](https://user-images.githubusercontent.com/74399067/192570412-1fc6acd6-d890-4f59-a14d-ad0c920860fa.png)
mistake on 343's end, the texture is messed up here for some reason
