### ISSUE TITLE
Weighting issues

### ISSUE THREAD

**Issue by Williaso** [Surasia/Infinite-Spartans-Pack#23]
Weighting issues under the armpits when arms are lifted
Weighting issue on right wrist, not an issue on left
![blender_ajVSyVZiBM](https://user-images.githubusercontent.com/114048681/191418416-708ca811-7211-4dff-8da7-761025e38477.png)
![image](https://user-images.githubusercontent.com/114048681/191418438-7e66bcc9-7eb6-4c09-96b7-553e9ae1b8d4.png)
![blender_NrM6jskE3s](https://user-images.githubusercontent.com/114048681/191418714-3036581a-f0f0-4b4f-9ffb-1ccea09684df.gif)

**Comment by Williaso** [comment]
![blender_WZTcxkxOQ5](https://user-images.githubusercontent.com/114048681/191419476-9cb5b4fd-6d7f-47e3-8289-97b7bbb0a214.gif)
Also this elbow isn't affected by the bone spinning, but the other one is

**Comment by Williaso** [comment]
![blender_KsExUMtGR5](https://user-images.githubusercontent.com/114048681/191420067-955174bc-11e1-4fbe-a73c-0ed292b0ee86.gif)
This hand affects the elbow, the other does not

**Comment by Williaso** [comment]
![blender_e8qPb1wgoE](https://user-images.githubusercontent.com/114048681/191421651-8e1c98d1-54ba-44a9-a286-647c65f30f61.gif)
Toes are not weighted

**Comment by Sierra-D421** [comment]
Yeah, the neck has a problem with stretching when I turn the helmet, too. I'll get a cap of it when I get the chance, but it's bad.

**Comment by Surasia** [comment]
All of these have been fixed and will come in Preview 3
