### ISSUE TITLE
Right Mark V Shoulder UV Issue

### ISSUE THREAD

**Issue by ballsgamer** [Surasia/Infinite-Spartans-Pack#24]
![image](https://user-images.githubusercontent.com/87114672/192127862-baf3a568-fd55-4821-a94b-949206805412.png)
![image](https://user-images.githubusercontent.com/87114672/192127875-ff68b119-a8bd-4280-8aa2-567ee9512dea.png)
The UV mapping is miss aligned for the right Mark V shoulder. its pretty simple fix though.

**Comment by Surasia** [comment]
![image](https://user-images.githubusercontent.com/74399067/192569354-533bdc76-5c91-46e3-8031-c0bc81d1cfde.png)
fixed
