### ISSUE TITLE
Mark V(B) "Fascia" Attachment is placed too low

### ISSUE THREAD

**Issue by diosrekmuka** [Surasia/Infinite-Spartans-Pack#25]
As the title says, that attachment sits too low on the Commando helmet. Simple fix, just bringing it to attention

**Comment by Surasia** [comment]
![image](https://user-images.githubusercontent.com/74399067/194755583-d67f895c-a0fb-40fd-92bc-2a548e539e7d.png)
Every helmet is adjusted to its API preview, so for FCI Fascia it is the COMMANDO Helmet.
