### ISSUE TITLE
4 Iron Eagle Strike Torso Attatchments not connected to rig

### ISSUE THREAD

**Issue by JustFredrik** [Surasia/Infinite-Spartans-Pack#3]
Journeyman, Jacknife, CloudJumper and Dog Harness does not scale or deform to the rig properly.
![iron eagle](https://user-images.githubusercontent.com/54528582/168676560-4fea3974-f644-41a4-b2be-1d9d0dce6e21.png)

**Comment by AverageTrapEnthusiast** [comment]
Will be addressed in 1.01
Fixes for this particular issue are finished
Finishing fixes for other issues.
