### ISSUE TITLE
Yoroi Upper Arm [L] has one edge not deforming to rig.

### ISSUE THREAD

**Issue by JustFredrik** [Surasia/Infinite-Spartans-Pack#4]
The two verts / edge (see image) stays in place and does not deform with the rest of the mesh creating a warped pointy bit on the mesh whenever moving the Yoroi Upper Arm [L].

![deform edge](https://user-images.githubusercontent.com/54528582/168677814-46309922-3598-4aa8-bc65-a10506cf0b34.png)

**Comment by AverageTrapEnthusiast** [comment]
This issue will be addressed in 1.01 (to release later today)
Issue fix has been implemented and with it various other rigging issues with the arms have been addressed as well
