### ISSUE TITLE
Rakshasa Helmet Attachment Metashak Tallyho Translation issues

### ISSUE THREAD

**Issue by JustFredrik** [Surasia/Infinite-Spartans-Pack#5]
When moving the root or the head the Metashak Tallyho translates more than intended. Example: moving rig from origin 1 unit in X axis will move the attachment more than 1 unit making the attatchment float away from the spartan whenever the rig is slightly moved or adjusted.

![metashak translation](https://user-images.githubusercontent.com/54528582/168679823-33d97bea-4f29-422c-8c9b-2352471877be.png)

**Comment by AverageTrapEnthusiast** [comment]
Will be addressed in 1.01
Fixes for this particular issue are finished
Finishing fixes for other issues.
Additional work must be done on the Rakshasa neck in order to correct rigging errors.
